# Generated by Django 4.2.7 on 2023-11-10 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneno',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
