# Generated by Django 4.2.7 on 2023-11-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_phoneno_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneno',
            old_name='user_id',
            new_name='user',
        ),
    ]
