# Generated by Django 4.2.7 on 2023-11-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_user_id_phoneno_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneno',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_nos', to='user.user'),
        ),
    ]
