# Generated by Django 4.2.7 on 2023-11-10 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_passport_user_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Access',
            },
        ),
        migrations.AlterModelOptions(
            name='phoneno',
            options={'verbose_name_plural': 'Phone Nos'},
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.ManyToManyField(related_name='users', to='user.access'),
        ),
    ]
